# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
 vmImage: 'ubuntu-latest'
trigger:
- master
steps:
- task: CmdLine@2
  inputs:
     script: 'chmod -R 755 ./'
  displayName: 'Set Permissions'
- task: CmdLine@2
  inputs:
      script: './Run.command -run -project_location $(ProjectLocation) -release $(ReleaseName) -testset $(TestSetName)'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Execute CITS Test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(ProjectLocation)/Results/TestExecution/$(ReleaseName)/$(TestSetName)/Latest/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'API Test Run'
  displayName: 'Publish Reports'